//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsGarage
    {
        public int DetailsGarageID { get; set; }
        public int DetailID { get; set; }
        public int StorageID { get; set; }
    
        public virtual Details Details { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
